### ISSUE TITLE
GCC 12 build issue: `error: loop variable ‘keyType’ creates a copy from type ‘const std::pair<const KeyType, int>’ [-Werror=range-loop-construct]`

### ISSUE THREAD

**Issue by celticsamurai** [raleighlittles/Tourbox_Neo_Linux_Driver#2]
Hey whenever I try to use the make command, here's what happens:
`Consolidate compiler generated dependencies of target TourBox_Linux_Driver
[ 50%] Building CXX object CMakeFiles/TourBox_Linux_Driver.dir/main.cpp.o
In file included from /home/wayne/Tourbox_Linux_Driver/cpp/main.cpp:23:
/home/wayne/Tourbox_Linux_Driver/cpp/uinput_helper.hpp: In function ‘void registerKeyboardEvents(int)’:
/home/wayne/Tourbox_Linux_Driver/cpp/uinput_helper.hpp:87:21: error: loop variable ‘keyType’ creates a copy from type ‘const std::pair<const KeyType, int>’ [-Werror=range-loop-construct]
   87 |     for (const auto keyType : keyMap)
      |                     ^~~~~~~
/home/wayne/Tourbox_Linux_Driver/cpp/uinput_helper.hpp:87:21: note: use reference type to prevent copying
   87 |     for (const auto keyType : keyMap)
      |                     ^~~~~~~
      |                     &
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/TourBox_Linux_Driver.dir/build.make:76: CMakeFiles/TourBox_Linux_Driver.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/TourBox_Linux_Driver.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
`

**Comment by raleighlittles** [comment]
Hmm, I just tested this today and I wasn't able to reproduce this error, it builds fine for me.

![image](https://user-images.githubusercontent.com/2137201/198915779-5a805227-d6b2-4376-9979-4f8f5cee610f.png)

Can you check what version of GCC and what version of CMake you're running? Run `gcc --version` and `cmake --version`.

I'm using `gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0` and `cmake version 3.22.1`

@celticsamurai

**Comment by celticsamurai** [comment]
gcc (GCC) 12.2.0
cmake version 3.24.2
I'm using Arch Linux. Could that be making the difference?

**Comment by raleighlittles** [comment]
Figured it out. Your newer version of GCC added a new warning that wasn't on GCC version 11. I've since updated the code to fix it.

**Comment by celticsamurai** [comment]
Well, looks like since I now have GCC 13, it's giving me this error.
<code>
[ 50%] Building CXX object CMakeFiles/TourBox_Linux_Driver.dir/main.cpp.o
/home/wayne/Tourbox_Neo_Linux_Driver/cpp/main.cpp: In function ‘int main(int, char**)’:
/home/wayne/Tourbox_Neo_Linux_Driver/cpp/main.cpp:74:16: error: ‘uint8_t’ was not declared in this scope
   74 |     std::array<uint8_t, 1> readBuffer;
      |                ^~~~~~~
/home/wayne/Tourbox_Neo_Linux_Driver/cpp/main.cpp:24:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   23 | #include "uinput_helper.hpp"
  +++ |+#include <cstdint>
   24 | 
/home/wayne/Tourbox_Neo_Linux_Driver/cpp/main.cpp:74:26: error: template argument 1 is invalid
   74 |     std::array<uint8_t, 1> readBuffer;
      |                          ^
/home/wayne/Tourbox_Neo_Linux_Driver/cpp/main.cpp:89:71: error: request for member ‘begin’ in ‘readBuffer’, which is of non-class type ‘int’
   89 |         ssize_t bytesRead = read(serialPortFileDescriptor, readBuffer.begin(), 1);
      |                                                                       ^~~~~
/home/wayne/Tourbox_Neo_Linux_Driver/cpp/main.cpp:100:85: error: invalid types ‘int[int]’ for array subscript
  100 |             std::cout << std::hex << std::setfill('0') << std::setw(2) << readBuffer[0] << " " << readBuffer[1] << std::endl;
      |                                                                                     ^
/home/wayne/Tourbox_Neo_Linux_Driver/cpp/main.cpp:100:109: error: invalid types ‘int[int]’ for array subscript
  100 |             std::cout << std::hex << std::setfill('0') << std::setw(2) << readBuffer[0] << " " << readBuffer[1] << std::endl;
      |                                                                                                             ^
/home/wayne/Tourbox_Neo_Linux_Driver/cpp/main.cpp:102:31: error: invalid types ‘int[int]’ for array subscript
  102 |             switch (readBuffer[0])
      |                               ^
make[2]: *** [CMakeFiles/TourBox_Linux_Driver.dir/build.make:76: CMakeFiles/TourBox_Linux_Driver.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/TourBox_Linux_Driver.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
</code>

**Comment by raleighlittles** [comment]
@celticsamurai I can't reproduce this error, I'm running the latest Ubuntu version which still has GCC 11.4 installed.

It looks like the error is complaining about a missing include to `stdint.h` since that's where the `uint8_t` type is declared. I've added it in the latest commit: https://github.com/raleighlittles/Tourbox_Neo_Linux_Driver/commit/c797349b05942ce2957e629bc93c845202848b04

**Comment by celticsamurai** [comment]
Okay so after updating, I was able to compile it again.
