### ISSUE TITLE
Failed to open serial port file /dev/ttyUSB0

### ISSUE THREAD

**Issue by celticsamurai** [raleighlittles/Tourbox_Neo_Linux_Driver#3]
Hey it's me again. I was wondering what I could do to resolve this issue. It happens in Arch as well as Linux Mint.

**Comment by raleighlittles** [comment]
When you first connect the Tourbox, look at the output from `dmesg` and make sure you see it connect to /dev/ttyUSB0. You should see a line that looks like this:

`usb 1-4.4.1.4: cp210x converter now attached to ttyUSB0`

Do you see that line? If you do, can you try connecting to the device via terminal emulator (I use [picocom](https://linux.die.net/man/8/picocom), but any terminal emulator would work) -- does _that_ work?

@celticsamurai

**Comment by celticsamurai** [comment]
I'm not seeing that line in the dmesg command.

**Comment by raleighlittles** [comment]
Hmm, that's a problem. It means your device isn't connecting with your PC for some reason -- unless that serial connection is established, there's not going to be any communication with the device.

Do you see anything at all in dmesg when you plug in the device? @celticsamurai

**Comment by celticsamurai** [comment]
I connected it to one of the front ports of my PC. Could that be the cause?

**Comment by celticsamurai** [comment]
My computer seems to read it as "Bus 001 Device 016: ID 2e3c:5740 ArteryTek AT32 Virtual ComPort in FS Mode." Is that how it's supposed to look?

**Comment by raleighlittles** [comment]
No, that isn't the same device mapping that I had.

you should see:

* Silicon Labs CP210x UART Bridge
* STMicroelectronics Joystick in FS Mode

https://github.com/raleighlittles/Tourbox_Linux_Driver/blob/main/docs/lsusb/STMElectronics-in-Joystick-Mode.txt
https://github.com/raleighlittles/Tourbox_Linux_Driver/blob/main/docs/lsusb/Silicon-Labs-CP210x-Uart-Bridge.txt

Can you post the full dmesg output when you connect the device? Maybe there's a clue in there as to what the issue is and why it's not identifying properly. @celticsamurai

**Comment by celticsamurai** [comment]
Here's what I see:
'
[ 7097.035577] audit: type=1105 audit(1668892292.131:701): pid=18090 uid=1000 auid=1000 ses=3 msg='op=PAM:session_open grantors=pam_systemd_home,pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
[ 7097.050698] audit: type=1106 audit(1668892292.151:702): pid=18090 uid=1000 auid=1000 ses=3 msg='op=PAM:session_close grantors=pam_systemd_home,pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
[ 7097.050729] audit: type=1104 audit(1668892292.151:703): pid=18090 uid=1000 auid=1000 ses=3 msg='op=PAM:setcred grantors=pam_faillock,pam_permit,pam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
[ 7107.139469] usb 1-10.4: USB disconnect, device number 14
[ 7109.962378] audit: type=1101 audit(1668892305.061:704): pid=18125 uid=1000 auid=1000 ses=3 msg='op=PAM:accounting grantors=pam_unix,pam_permit,pam_time acct="wayne" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
[ 7109.962763] audit: type=1110 audit(1668892305.061:705): pid=18125 uid=1000 auid=1000 ses=3 msg='op=PAM:setcred grantors=pam_faillock,pam_permit,pam_env,pam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
[ 7109.963742] audit: type=1105 audit(1668892305.061:706): pid=18125 uid=1000 auid=1000 ses=3 msg='op=PAM:session_open grantors=pam_systemd_home,pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
[ 7109.970091] audit: type=1106 audit(1668892305.071:707): pid=18125 uid=1000 auid=1000 ses=3 msg='op=PAM:session_close grantors=pam_systemd_home,pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
[ 7109.970110] audit: type=1104 audit(1668892305.071:708): pid=18125 uid=1000 auid=1000 ses=3 msg='op=PAM:setcred grantors=pam_faillock,pam_permit,pam_env,pam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
[ 7112.067275] usb 1-10.4: new full-speed USB device number 15 using xhci_hcd
[ 7112.449112] usb 1-10.4: New USB device found, idVendor=2e3c, idProduct=5740, bcdDevice= 2.00
[ 7112.449117] usb 1-10.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 7112.449118] usb 1-10.4: Product: AT32 Virtual ComPort in FS Mode
[ 7112.449119] usb 1-10.4: Manufacturer: ArteryTek
[ 7112.449120] usb 1-10.4: SerialNumber: 77788D6B4000
[ 7112.478636] cdc_acm 1-10.4:1.0: ttyACM0: USB ACM device
[ 7114.917475] audit: type=1101 audit(1668892310.022:709): pid=18148 uid=1000 auid=1000 ses=3 msg='op=PAM:accounting grantors=pam_unix,pam_permit,pam_time acct="wayne" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
[ 7114.917763] audit: type=1110 audit(1668892310.022:710): pid=18148 uid=1000 auid=1000 ses=3 msg='op=PAM:setcred grantors=pam_faillock,pam_permit,pam_env,pam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
[ 7114.918730] audit: type=1105 audit(1668892310.022:711): pid=18148 uid=1000 auid=1000 ses=3 msg='op=PAM:session_open grantors=pam_systemd_home,pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
'

**Comment by raleighlittles** [comment]
Oh, I see.

`cdc_acm 1-10.4:1.0: ttyACM0: USB ACM device`

https://github.com/raleighlittles/Tourbox_Linux_Driver/blob/main/cpp/main.cpp#L40

Change that line to say "/dev/ttyACM0" instead of "/dev/ttyUSB0". (In the next commit I'll fix it more elegantly)

@celticsamurai

**Comment by celticsamurai** [comment]
Welp...
`Failed to open serial port file /dev/ttyACM0`

**Comment by raleighlittles** [comment]
@celticsamurai and you're sure you're running the program as root (sudo)? Besides that, I truly don't know what the issue could be -- if the file exists, and even with root you can't get a file descriptor to it, I don't know how to troubleshoot that.

**Comment by sjkillen** [comment]
Using `/dev/ttyACM0` does not give me an error, but instead reads to the device always result in EOF

**Comment by sjkillen** [comment]
I tinkered with it for a little while, serial programming is new to me but I found it odd that running
```bash
sudo stty -F /dev/ttyACM0 
```
after running the program yielded
```bash
speed 115200 baud; line = 0;
intr = <undef>; quit = <undef>; erase = <undef>; kill = <undef>; eof = <undef>; start = <undef>; stop = <undef>; susp = <undef>; rprnt = <undef>; werase = <undef>; lnext = <undef>; discard = <undef>; min = 0; time = 0;
-brkint -icrnl -imaxbel
-opost -onlcr
-isig -icanon -iexten -echo -echoe -echok -echoctl -echoke
```
-cread is no where to be found despite it being set here
https://github.com/raleighlittles/Tourbox_Linux_Driver/blob/7779f5af0a11020a506609031ad5d1bcffd590bf/cpp/main.cpp#L53

**Comment by celticsamurai** [comment]
> @celticsamurai and you're sure you're running the program as root (sudo)? Besides that, I truly don't know what the issue could be -- if the file exists, and even with root you can't get a file descriptor to it, I don't know how to troubleshoot that.

Okay looks like that was the problem. Thank you so much!
